# Generated by Django 5.1.7 on 2025-03-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hakkımda', max_length=100)),
                ('name', models.CharField(default='Sercan Uysal', max_length=100)),
                ('short_description', models.TextField(blank=True, help_text='Kısa ve öz bir giriş cümlesi.')),
                ('detailed_description', models.TextField(help_text='Ayrıntılı hakkımda bilgisi.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('tools', models.CharField(blank=True, help_text='Kullanılan araçları virgülle ayırarak yazın.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hakkımda',
                'verbose_name_plural': 'Hakkımda Bilgileri',
            },
        ),
    ]
