# Generated by Django 5.1.7 on 2025-03-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Skills', max_length=100)),
                ('subtitle', models.CharField(default='Every Day is a New Challenge', max_length=150)),
                ('description', models.TextField()),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='Contact Me', max_length=50)),
                ('button_link', models.CharField(default='#contact', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Bölümü',
                'verbose_name_plural': 'Skill Bölümleri',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency_percentage', models.PositiveIntegerField(default=50, help_text='Yüzde olarak beceri seviyesi (0-100)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.skillsection')),
            ],
            options={
                'verbose_name': 'Beceri',
                'verbose_name_plural': 'Beceriler',
            },
        ),
    ]
