# Generated by Django 5.1.7 on 2025-03-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skillsection_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Proje Kategorisi',
                'verbose_name_plural': 'Proje Kategorileri',
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Proje Kategorisi', 'verbose_name_plural': 'Proje Kategorileri'},
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField(blank=True, help_text='Opsiyonel proje bağlantısı (Youtube veya web sitesi).', max_length=500, null=True)),
                ('is_video', models.BooleanField(default=False, help_text='Eğer link video ise bu alanı işaretleyin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.projectcategory')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
    ]
