# Generated by Django 5.1.7 on 2025-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactinfo_contactmessage_sociallink_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Kapak Resmi')),
                ('summary', models.TextField(max_length=400, verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayınlansın mı?')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
    ]
