# Generated by Django 5.1.7 on 2025-03-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
