# Generated by Django 5.1.7 on 2025-03-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_skillsection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Skill bölümünün aktif olup olmadığını belirler.'),
        ),
    ]
